
spring:
  application:
    name: config-prod
    
eureka:
  instance:
    preferIpAddress:true
  client:
    register-with-eureka: true
    fetch-registry: true
  serviceUrl :
      defaultZone=http://localhost:8761/eureka

